# .goreleaser.yml
# Build customization
builds:
  - binary: gtrello
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
        
# Release customization
release:
  github:
    owner: midorigreen
    name: gtrello
